Models/ErrorViewModel.cs
namespace BancoEleitoresWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;

namespace BancoEleitoresWeb.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar()
        {
            return View();
        }

        public IActionResult Detalhes()
        {
            return View();
        }

        public IActionResult ApagarConfirma()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using BancoEleitoresWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BancoEleitoresWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Contato/Criar.cshtml
@{
    ViewData["Title"] = "Criar novo contatos";
}

<h1>Novo Contato</h1>


<br />

<form asp-controller="Contato" asp-action="Criar" method="post">

    <div class="row g-3" method="get" action=".">

        <div class="col-sm-6">
            <input type="text" class="form-control" placeholder="Nome completo" id="nome">
        </div>

        <div class="col-sm-2">
            <input type="text" class="form-control" placeholder="Pseudonimo" id="pseudonimo">
        </div>

        <div class="col-sm-2">
            <input type="text" class="form-control" placeholder="CPF" id="cpf">
        </div>

    </div>

    <br />

    <div class="row g-3" method="get" action=".">

        <div class="col-sm-2" id="sexo">
            <select class="form-select">
                <option selected>Sexo</option>
                <option value="Masculino">Masculino</option>
                <option value="Feminino">Feminino</option>
            </select>
        </div>

        <div class="col-sm-2">
            <input type="text" class="form-control" placeholder="Nascimento" id="nascimento">
        </div>

        <div class="col-sm-2" id="filhos">
            <select class="form-select">
                <option selected>Tem filhos?</option>
                <option value="Não">Não</option>
                <option value="Sim">Sim</option>
            </select>
        </div>

        <div class="col-sm-3">
            <input type="text" class="form-control" placeholder="Profissão" id="profissao">
        </div>

    </div>

    <br />

    <div>

        <div class="row g-3" method="get" action=".">

            <div class="col-sm-2">
                <input type="text" class="form-control" placeholder="CEP" name="cep" id="cep" size="10">
            </div>

        </div>

        <br />

        <div class="row g-3" method="get" action=".">

            <div class="col-sm-6">

                <input type="text" class="form-control" placeholder="Logradouro" id="nome">

            </div>

            <div class="col-sm-2">
                <input type="text" class="form-control" placeholder="Número" id="numero">
            </div>

            <div class="col-sm-4">
                <input type="text" class="form-control" placeholder="Complemento" id="complemento">
            </div>


            <div class="col-sm-4">
                <input name="bairro" type="text" class="form-control" placeholder="Bairro" id="bairro">
            </div>


            <div class="col-sm-3">
                <input name="cidade" type="text" class="form-control" placeholder="Cidade" id="cidade">
            </div>


            <div class="col-sm-2">
                <input name="uf" type="text" class="form-control" placeholder="UF" id="uf">
            </div>

        </div>

    </div>

    <br />

    <div class="d-grid gap-2 col-6 mx-auto">
        <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
        <a class="btn btn-secondary btn-block" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
    </div>

</form>

Views/Contato/Index.cshtml
@{
    ViewData["Title"] = "Lista de contatos";
}

<br />

<a class="btn btn-primary" role="button" asp-controller="Contato" asp-action="Criar">Adicionar contato</a>

<br />

<div class="text-center">

    <h1>Lista de contatos</h1>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Fone</th>
                <th scope="col">Instagram</th>
                <th scope="col">Twitter</th>
                <th scope="col">Cidade</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>João</td>
                <td>11 98765-0987</td>
                <td>linkInstagram</td>
                <td>linkTwitter</td>
                <td>São José</td>
                <td>
                    <div class="btn-group" role="group">
                        <a role="button" class="btn btn-primary">Detalhes</a>
                        <a role="button" class="btn btn-danger">Apagar</a>
                    </div>
                </td>
            </tr>
            <tr>
                <th scope="row">2</th>
                <td>Maria</td>
                <td>11 98765-0987</td>
                <td>linkInstagram</td>
                <td>linkTwitter</td>
                <td>São José</td>
                <td>
                    <div class="btn-group" role="group">
                        <a role="button" class="btn btn-primary">Detalhes</a>
                        <a role="button" class="btn btn-danger">Apagar</a>
                    </div>
                </td>
            </tr>
            <tr>
                <th scope="row">3</th>
                <td>Jesus</td>
                <td>11 98765-0987</td>
                <td>linkInstagram</td>
                <td>linkTwitter</td>
                <td>São José</td>
                <td>
                    <div class="btn-group" role="group">
                        <a role="button" class="btn btn-primary">Detalhes</a>
                        <a role="button" class="btn btn-danger">Apagar</a>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>


</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Sistema Eleitores Web";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo!</h1>
    
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema Eleitores Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BancoEleitoresWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sistema Eleitores Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Contatos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BancoEleitoresWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>